/** Copy for the provider and route workspace, composed into the main dictionaries. */
export const managementEn: Record<string, string> = {
  managementProviderIntro: 'Connect your AI providers and keep every upstream in one place.',
  managementTotalProviders: 'Total providers',
  managementEnabledProviders: 'Enabled providers',
  managementProtocols: 'Protocols',
  managementSearchProviders: 'Search providers or models…',
  managementFilterStatus: 'Filter by provider status',
  managementFilterall: 'All providers',
  managementFilterenabled: 'Enabled',
  managementFilterdisabled: 'Disabled',
  managementKeyConfigured: 'Key configured',
  managementToggleProvider: 'Enable provider {id}',
  managementRemoveProvider: 'Remove provider {id}',
  managementEnabled: 'Enabled',
  managementDisabled: 'Disabled',
  managementPriority: 'Priority',
  managementNoModels: 'No models configured',
  managementSaveToProbe: 'Save your provider changes before testing the connection.',
  managementNoMatches: 'No matching results',
  managementNoMatchesHint: 'Try a different search or clear your filters.',
  managementEmptyProviders: 'Your first connection starts here',
  managementEmptyProvidersHint: 'Add an upstream provider to connect your models to literouter.',
  managementResetFilters: 'Clear filters',
  managementRouteIntro: 'Give your models a single name and a reliable path to every provider.',
  managementFailoverTitle: 'Ordered failover',
  managementSearchRoutes: 'Search models or target providers…',
  managementTargetCount: '{n} targets in the chain',
  managementToggleRoute: 'Enable route {model}',
  managementEditRoute: 'Edit route {model}',
  managementRemoveRoute: 'Remove route {model}',
  managementPrimary: 'First choice',
  managementFallback: 'Fallback',
  managementMissingProvider: 'Provider missing',
  managementNoTargets: 'No targets configured',
  managementRouteDisabled: 'This route is disabled.',
  managementEmptyRoutes: 'Build a route for your model',
  managementEmptyRoutesHint: 'Map a model name to one or more providers, then choose the order they are tried.',
  managementConnection: 'Connection',
  managementModelsPricing: 'Models',
  managementTraffic: 'Traffic',
  managementAdvanced: 'Advanced',
  managementProviderDialogHint: 'Connection, models and traffic controls for your upstream provider.',
  managementProviderSections: 'Provider settings sections',
  managementProviderId: 'Provider ID',
  managementDisplayName: 'Display name',
  managementProtocol: 'Protocol',
  managementAvailability: 'Availability',
  managementProviderEnabled: 'Enable this provider',
  managementApiVersion: 'API version',
  managementRegion: 'Region',
  managementProject: 'Project ID',
  managementCredentialsFile: 'Credentials file',
  managementAwsAccessKey: 'AWS access key ID',
  managementAwsSecret: 'AWS secret access key',
  managementAwsSession: 'AWS session token',
  managementStreaming: 'Streaming',
  managementSupportsStreaming: 'Supports streaming responses',
  managementPricing: 'Token pricing',
  managementInputPrice: 'Input · USD / 1M tokens',
  managementOutputPrice: 'Output · USD / 1M tokens',
  managementWeight: 'Weight',
  managementRequestTimeout: 'Request timeout (seconds)',
  managementConnectTimeout: 'Connection timeout (seconds)',
  managementConcurrency: 'Concurrent request limit',
  managementRequestsMinute: 'Requests per minute',
  managementHeaders: 'Custom headers',
  managementChatPath: 'Chat endpoint path',
  managementEmbeddingsPath: 'Embeddings endpoint path',
  managementNote: 'Notes',
  managementDraftHint: 'Save your changes to make them live.',
  managementRouteDialogHint: 'Choose a model name and arrange its upstream providers.',
  managementPublicModel: 'Public model name',
  managementPublicModelHint: 'The model name your clients use when sending a request.',
  managementAddProviderFirst: 'Add a provider first, then select it as a route target.',
  managementMoveTargetUp: 'Move target {n} up',
  managementMoveTargetDown: 'Move target {n} down',
  managementRemoveTarget: 'Remove target {n}',
  managementTargetProviderLabel: 'Provider for target {n}',
  managementSelectProvider: 'Select a provider',
  managementUpstreamModel: 'Upstream model (optional)',
  managementKeepModel: 'Keep the public model name',
  managementTargetModelLabel: 'Upstream model for target {n}',
}

export const managementZh: Record<string, string> = {
  managementProviderIntro: '连接你的 AI 服务，在一个地方管理所有上游中转站。',
  managementTotalProviders: '全部中转站',
  managementEnabledProviders: '已启用',
  managementProtocols: '接入协议',
  managementSearchProviders: '搜索中转站或模型…',
  managementFilterStatus: '按中转站状态筛选',
  managementFilterall: '全部中转站',
  managementFilterenabled: '已启用',
  managementFilterdisabled: '已停用',
  managementKeyConfigured: '已填写密钥',
  managementToggleProvider: '启用中转站 {id}',
  managementRemoveProvider: '移除中转站 {id}',
  managementEnabled: '已启用',
  managementDisabled: '已停用',
  managementPriority: '优先级',
  managementNoModels: '尚未配置模型',
  managementSaveToProbe: '保存中转站的修改后即可探测连接。',
  managementNoMatches: '没有找到匹配的结果',
  managementNoMatchesHint: '试试其他关键词，或清除筛选条件。',
  managementEmptyProviders: '从第一个连接开始',
  managementEmptyProvidersHint: '添加一个上游中转站，将你的模型接入 literouter。',
  managementResetFilters: '清除筛选',
  managementRouteIntro: '统一模型名称，清晰安排每一次请求的转发路径。',
  managementFailoverTitle: '按顺序自动故障转移',
  managementSearchRoutes: '搜索模型或候选中转站…',
  managementTargetCount: '候选链包含 {n} 个目标',
  managementToggleRoute: '启用路由 {model}',
  managementEditRoute: '编辑路由 {model}',
  managementRemoveRoute: '移除路由 {model}',
  managementPrimary: '首选',
  managementFallback: '备用',
  managementMissingProvider: '中转站不存在',
  managementNoTargets: '尚未配置候选目标',
  managementRouteDisabled: '此路由已停用。',
  managementEmptyRoutes: '为模型建立一条路由',
  managementEmptyRoutesHint: '将一个模型名称映射到多个中转站，并安排它们的尝试顺序。',
  managementConnection: '连接设置',
  managementModelsPricing: '模型与定价',
  managementTraffic: '流量控制',
  managementAdvanced: '高级设置',
  managementProviderDialogHint: '配置上游连接、可用模型与流量规则。',
  managementProviderSections: '中转站设置分类',
  managementProviderId: '中转站标识',
  managementDisplayName: '显示名称',
  managementProtocol: '协议',
  managementAvailability: '启用状态',
  managementProviderEnabled: '启用此中转站',
  managementApiVersion: 'API 版本',
  managementRegion: '区域',
  managementProject: '项目 ID',
  managementCredentialsFile: '凭据文件',
  managementAwsAccessKey: 'AWS Access Key ID',
  managementAwsSecret: 'AWS Secret Access Key',
  managementAwsSession: 'AWS 会话令牌',
  managementStreaming: '流式响应',
  managementSupportsStreaming: '支持流式响应',
  managementPricing: 'Token 定价',
  managementInputPrice: '输入 · 美元 / 百万 Token',
  managementOutputPrice: '输出 · 美元 / 百万 Token',
  managementWeight: '权重',
  managementRequestTimeout: '请求超时（秒）',
  managementConnectTimeout: '连接超时（秒）',
  managementConcurrency: '并发请求上限',
  managementRequestsMinute: '每分钟请求上限',
  managementHeaders: '自定义请求头',
  managementChatPath: '对话接口路径',
  managementEmbeddingsPath: '向量接口路径',
  managementNote: '备注',
  managementDraftHint: '保存修改后生效。',
  managementRouteDialogHint: '设置模型名称，并安排上游中转站的尝试顺序。',
  managementPublicModel: '对外模型名称',
  managementPublicModelHint: '客户端发送请求时使用的模型名称。',
  managementAddProviderFirst: '请先添加中转站，再将其选为路由候选目标。',
  managementMoveTargetUp: '上移第 {n} 个目标',
  managementMoveTargetDown: '下移第 {n} 个目标',
  managementRemoveTarget: '移除第 {n} 个目标',
  managementTargetProviderLabel: '第 {n} 个目标的中转站',
  managementSelectProvider: '选择中转站',
  managementUpstreamModel: '上游模型（可选）',
  managementKeepModel: '沿用对外模型名称',
  managementTargetModelLabel: '第 {n} 个目标的上游模型',
}
