export const activityEn: Record<string, string> = {
  settingsIntro: 'Make this gateway work the way you do.',
  settingsNavigation: 'Settings sections',
  settingsConnection: 'Connection & access',
  settingsConnectionNote: 'Choose where your gateway listens and how you connect to it.',
  settingsRouting: 'Routing & resilience',
  settingsRoutingNote: 'Control how requests find a relay and recover from upstream failures.',
  settingsCache: 'Response cache',
  settingsCacheNote: 'Reuse identical non-streaming responses to reduce latency and upstream usage.',
  settingsTelemetry: 'Logs & telemetry',
  settingsTelemetryNote: 'Choose what to keep, how long to keep it, and where to send metrics.',
  settingsConfig: 'Configuration file',
  settingsConfigNote: 'Review your current draft, or move your configuration between environments.',
  settingsDraftNote: 'Changes stay in your draft until you save them.',
  settingsListener: 'Listener',
  settingsAccess: 'Access & security',
  settingsConsole: 'Console & updates',
  settingsCircuit: 'Circuit breaker',
  settingsLogStorage: 'Log storage',
  settingsTraffic: 'Traffic history',
  settingsMetrics: 'Metrics export',
  settingsRestart: 'Listener and TLS changes take effect after a restart.',
  settingsCurrentEndpoint: 'Currently running model endpoint',
  operationFailed: 'Operation failed: {detail}',
  saveRefreshFailed: 'Configuration saved, but refreshing it failed: {detail}',
  importNotConfig: 'This file contains no server, providers, or routes; the draft was kept.',
  importInvalidField: 'Invalid type at {path}; the draft was kept.',
  hintFailureThreshold: 'Open the circuit after this many consecutive failures; 0 disables circuit breaking.',
  hintCacheEntries: 'Applies when cache TTL is above 0; least recently used entries are evicted at this limit.',
  hintBodyLimit: 'Applies when body logging is enabled; maximum retained bytes per request or response body; 0 retains no body.',
  settingHost: 'Listen address',
  settingPort: 'Port',
  settingTlsCert: 'TLS certificate path',
  settingTlsKey: 'TLS private key path',
  settingWebUi: 'Web console',
  settingReload: 'Automatic configuration reload',
  settingPolicy: 'Routing policy',
  settingAttempts: 'Maximum attempts',
  settingDeadline: 'Request deadline · seconds',
  settingAffinity: 'Session affinity · seconds',
  settingPassthrough: 'Pass through unknown models',
  settingSkipCircuits: 'Skip open circuits',
  settingFailureThreshold: 'Failures before opening',
  settingCooldown: 'Cooldown · seconds',
  settingCacheTtl: 'Cache lifetime · seconds',
  settingCacheEntries: 'Maximum cached responses',
  settingLogCapacity: 'Log entry capacity',
  settingLogBodies: 'Capture request and response bodies',
  settingBodyLimit: 'Maximum body size · bytes',
  settingPersist: 'Keep telemetry across restarts',
  settingBucketSec: 'Time per bucket · seconds',
  settingBucketCount: 'Number of history buckets',
  settingOtlp: 'OpenTelemetry endpoint',
  settingOn: 'Enabled',
  settingOff: 'Disabled',
  policyPriority: 'Priority first',
  policyFastest: 'Fastest relay',
  policyCheapest: 'Lowest price',
  policyRoundRobin: 'Balanced round-robin',
  configDraft: 'Current draft',
  configDraftNote: 'Stored secrets remain redacted. Newly entered values are included in this draft.',
  configSource: 'Configuration location',
  configInMemory: 'In-memory configuration',
  configCopyFailed: 'Could not copy. Select the configuration and copy it manually.',
  activityIntro: 'Follow every request, from the first connection to the final response.',
  activityTitle: 'Request activity',
  activityLive: 'Live updates',
  activityPaused: 'Updates paused',
  activityOffline: 'Waiting for connection',
  activitySearch: 'Search model, relay or request ID…',
  activityCount: 'Showing {shown} of {total} entries',
  activityNewest: 'Newest first',
  activityFilterLevel: 'Filter by level',
  activityFilterKind: 'Filter by kind',
  activityReset: 'Reset filters',
  activityEmpty: 'Your activity starts here',
  activityEmptyNote: 'Requests and gateway events appear here as they arrive.',
  activityNoResults: 'No matching activity',
  activityNoResultsNote: 'Try another search or adjust your filters.',
  activityInspect: 'View request details',
  activityDetails: 'Request details',
  activityDetailsNote: 'Timing, routing and status for this gateway event.',
  activityRequestId: 'Request ID',
  activityUpstream: 'Upstream model',
  activityAttempt: 'Attempt',
  activityPayload: 'Response size',
  activityTiming: 'Timing breakdown',
  activityMessage: 'Event message',
  activityStream: 'Streaming',
  activityFailover: 'Failover',
  activityClose: 'Close',
  activityLevelInfo: 'Info',
  activityLevelWarn: 'Warning',
  activityLevelError: 'Error',
  activityKindChat: 'Chat',
  activityKindResponses: 'Responses',
  activityKindAnthropic: 'Anthropic Messages',
  activityKindGemini: 'Gemini',
  activityKindGeminiStream: 'Gemini streaming',
  activityClearView: 'Clear this log view',
  activityRequestBody: 'Request body',
  activityResponseBody: 'Response body',
  activityBodiesNote: 'Captured bodies are redacted and may be truncated to the configured size limit.',
  activityBodiesAbsent: 'No body was captured for this event. Body logging only applies to future requests and does not capture binary media.',
  activityConfigureBodies: 'Configure body logging',
  activityKindEmbeddings: 'Embeddings',
  activityKindModels: 'Models',
  activityKindAdmin: 'Management',
  activityKindSystem: 'System',
  keyConnect: 'Connect to your gateway',
  keyConnectAction: 'Connect',
  keyBrowserNote: 'This credential is saved only in this browser.',
  keyHide: 'Hide key',
  keyReveal: 'Show key',
}

export const activityZh: Record<string, string> = {
  settingsIntro: '让网关按照你的方式运行。',
  settingsNavigation: '设置分区',
  settingsConnection: '连接与访问',
  settingsConnectionNote: '设置网关监听地址、访问凭据与控制台。',
  settingsRouting: '路由与容错',
  settingsRoutingNote: '控制请求的中转站选择，以及上游故障后的恢复方式。',
  settingsCache: '响应缓存',
  settingsCacheNote: '复用相同非流式请求的响应，降低延迟与上游用量。',
  settingsTelemetry: '日志与遥测',
  settingsTelemetryNote: '管理日志留存、流量历史与指标导出。',
  settingsConfig: '配置文件',
  settingsConfigNote: '查看当前草稿，或在不同环境间迁移配置。',
  settingsDraftNote: '所有改动先保留在草稿中，保存后才会生效。',
  settingsListener: '服务监听',
  settingsAccess: '访问与安全',
  settingsConsole: '控制台与更新',
  settingsCircuit: '熔断保护',
  settingsLogStorage: '日志留存',
  settingsTraffic: '流量历史',
  settingsMetrics: '指标导出',
  settingsRestart: '监听地址与 TLS 变更在重启后生效。',
  settingsCurrentEndpoint: '当前运行中的模型接口',
  operationFailed: '操作失败：{detail}',
  saveRefreshFailed: '配置已保存，但读取最新状态失败：{detail}',
  importNotConfig: '该文件不包含 server、providers 或 routes，未替换草稿。',
  importInvalidField: '配置字段 {path} 的类型无效，未替换草稿。',
  hintFailureThreshold: '连续失败达到此次数后熔断；0 关闭熔断。',
  hintCacheEntries: '仅在缓存时长大于 0 时生效；超出上限会淘汰最久未使用的条目。',
  hintBodyLimit: '仅在记录请求/响应体开启时生效，每个请求体或响应体最多保留此字节数；0 不保留正文。',
  settingHost: '监听地址',
  settingPort: '端口',
  settingTlsCert: 'TLS 证书路径',
  settingTlsKey: 'TLS 私钥路径',
  settingWebUi: 'Web 控制台',
  settingReload: '自动重载配置',
  settingPolicy: '路由策略',
  settingAttempts: '最多尝试次数',
  settingDeadline: '请求时限 · 秒',
  settingAffinity: '会话亲和时长 · 秒',
  settingPassthrough: '透传未知模型',
  settingSkipCircuits: '跳过已熔断中转站',
  settingFailureThreshold: '触发熔断的失败次数',
  settingCooldown: '熔断冷却时间 · 秒',
  settingCacheTtl: '缓存有效期 · 秒',
  settingCacheEntries: '最多缓存响应数',
  settingLogCapacity: '日志容量 · 条',
  settingLogBodies: '记录请求与响应正文',
  settingBodyLimit: '正文长度上限 · 字节',
  settingPersist: '重启后保留遥测数据',
  settingBucketSec: '每个时间桶的宽度 · 秒',
  settingBucketCount: '历史时间桶数量',
  settingOtlp: 'OpenTelemetry 端点',
  settingOn: '已启用',
  settingOff: '已关闭',
  policyPriority: '优先级优先',
  policyFastest: '延迟最低',
  policyCheapest: '价格最低',
  policyRoundRobin: '平均分流',
  configDraft: '当前草稿',
  configDraftNote: '已存密钥保持脱敏；本次新输入的内容会包含在草稿中。',
  configSource: '配置文件位置',
  configInMemory: '内存配置',
  configCopyFailed: '复制失败，请选择配置内容后手动复制。',
  activityIntro: '从连接建立到响应完成，了解每一次请求。',
  activityTitle: '请求活动',
  activityLive: '实时更新中',
  activityPaused: '已暂停更新',
  activityOffline: '等待连接',
  activitySearch: '搜索模型、中转站或请求 ID…',
  activityCount: '显示 {shown} / {total} 条记录',
  activityNewest: '最新优先',
  activityFilterLevel: '按级别筛选',
  activityFilterKind: '按类型筛选',
  activityReset: '重置筛选',
  activityEmpty: '从第一条请求开始',
  activityEmptyNote: '请求与网关事件到达后，会实时出现在这里。',
  activityNoResults: '没有匹配的活动',
  activityNoResultsNote: '试试其他关键词，或调整筛选条件。',
  activityInspect: '查看请求详情',
  activityDetails: '请求详情',
  activityDetailsNote: '查看这次网关事件的耗时、路由与响应状态。',
  activityRequestId: '请求 ID',
  activityUpstream: '上游模型',
  activityAttempt: '尝试次数',
  activityPayload: '响应大小',
  activityTiming: '耗时分布',
  activityMessage: '事件信息',
  activityStream: '流式',
  activityFailover: '故障转移',
  activityClose: '关闭',
  activityLevelInfo: '信息',
  activityLevelWarn: '警告',
  activityLevelError: '错误',
  activityKindChat: '对话',
  activityKindResponses: 'Responses',
  activityKindAnthropic: 'Anthropic 消息',
  activityKindGemini: 'Gemini',
  activityKindGeminiStream: 'Gemini 流式',
  activityClearView: '清空当前日志视图',
  activityRequestBody: '请求正文',
  activityResponseBody: '响应正文',
  activityBodiesNote: '已记录的正文经过脱敏，可能按配置的长度上限截断。',
  activityBodiesAbsent: '这条日志没有记录正文。正文记录只对之后的请求生效，也不记录二进制媒体内容。',
  activityConfigureBodies: '设置正文记录',
  activityKindEmbeddings: '向量',
  activityKindModels: '模型',
  activityKindAdmin: '管理',
  activityKindSystem: '系统',
  keyConnect: '连接你的网关',
  keyConnectAction: '连接',
  keyBrowserNote: '此凭据仅保存在当前浏览器中。',
  keyHide: '隐藏密钥',
  keyReveal: '显示密钥',
}
