/** Overview copy lives together so the dashboard and its charts share a voice. */
export const overviewEn: Record<string, string> = {
  overviewTitle: 'Your gateway, at a glance',
  overviewDescription: 'A clear view of your traffic, performance, and connected models.',
  overviewLive: 'Live telemetry',
  overviewOffline: 'Connection interrupted',
  overviewViewLogs: 'View request logs',
  overviewWaiting: 'Waiting for your gateway',
  overviewWaitingDescription: 'Connect to the local service to see your traffic and relay health here.',
  overviewTraffic: 'Request activity',
  overviewTrafficDescription: 'Traffic through your gateway over time.',
  overviewWindow: '{window} window',
  overviewBucket: 'Each interval: {interval}',
  overviewInterval: 'Selected interval',
  overviewNoTraffic: 'Ready for your first request',
  overviewNoTrafficDescription: 'Your traffic will appear here as requests reach the gateway.',
  overviewTrafficChart: 'Request activity: {requests} requests and {failures} failures across {buckets} intervals.',
  overviewRuntime: 'Gateway status',
  overviewRuntimeDescription: 'Performance and runtime',
  overviewRunning: 'Running',
  overviewStopped: 'Stopped',
  overviewEwma: 'Moving average',
  overviewCache: 'Response cache',
  overviewCacheMisses: 'Cache misses',
  overviewEnabled: 'Enabled',
  overviewDisabled: 'Disabled',
  overviewEndpointDescription: 'OpenAI-compatible client Base URL, including /v1.',
  overviewCopyEndpoint: 'Copy client Base URL',
  overviewInspectRelay: 'View activity for {provider}',
  overviewConfigPath: 'Configuration file',
  overviewHealthDescription: 'Availability and performance across your upstream relays.',
  overviewManageRelays: 'Manage relays',
  overviewRelaysCount: '{n} relays',
  overviewNoRelays: 'Connect your first relay',
  overviewNoRelaysDescription: 'Add an upstream provider to start routing requests through literouter.',
  overviewHealthy: 'Healthy',
  overviewDegraded: 'Degraded',
  overviewOpen: 'Circuit open',
  overviewUnknown: 'Not measured',
  overviewProbeRelay: 'Test {provider}',
  overviewMoreMetrics: 'More metrics',
  overviewP95: 'p95 latency',
  overviewNoError: 'No error recorded',
  overviewModelDescription: 'Models exposed by your gateway and their upstream targets.',
  overviewManageRoutes: 'Manage routes',
  overviewModelsCount: '{n} models',
  overviewNoModels: 'No models available yet',
  overviewNoModelsDescription: 'Configure a relay and model routes to make models available here.',
  overviewDirectModel: 'Available through the gateway',
}

export const overviewZh: Record<string, string> = {
  overviewTitle: '网关运行，一目了然',
  overviewDescription: '掌握请求流量、运行表现与模型连接状态。',
  overviewLive: '实时遥测',
  overviewOffline: '连接已中断',
  overviewViewLogs: '查看请求日志',
  overviewWaiting: '正在等待网关连接',
  overviewWaitingDescription: '连接本地服务后，即可在这里查看流量与中转站状态。',
  overviewTraffic: '请求趋势',
  overviewTrafficDescription: '查看流经网关的请求随时间的变化。',
  overviewWindow: '{window} 时间窗口',
  overviewBucket: '每个区间：{interval}',
  overviewInterval: '所选区间',
  overviewNoTraffic: '准备好接收第一个请求',
  overviewNoTrafficDescription: '请求到达网关后，流量趋势将在这里显示。',
  overviewTrafficChart: '请求趋势：{buckets} 个区间内有 {requests} 次请求、{failures} 次失败。',
  overviewRuntime: '网关状态',
  overviewRuntimeDescription: '性能与运行信息',
  overviewRunning: '运行中',
  overviewStopped: '已停止',
  overviewEwma: '移动平均',
  overviewCache: '应答缓存',
  overviewCacheMisses: '缓存未命中',
  overviewEnabled: '已启用',
  overviewDisabled: '已关闭',
  overviewEndpointDescription: '用于 OpenAI 兼容客户端的 Base URL，已包含 /v1。',
  overviewCopyEndpoint: '复制客户端 Base URL',
  overviewInspectRelay: '查看 {provider} 的请求日志',
  overviewConfigPath: '配置文件',
  overviewHealthDescription: '各上游中转站的可用性与实际运行表现。',
  overviewManageRelays: '管理中转站',
  overviewRelaysCount: '{n} 个中转站',
  overviewNoRelays: '连接第一个中转站',
  overviewNoRelaysDescription: '添加上游服务商，即可通过 literouter 转发请求。',
  overviewHealthy: '健康',
  overviewDegraded: '异常',
  overviewOpen: '已熔断',
  overviewUnknown: '待观测',
  overviewProbeRelay: '探测 {provider}',
  overviewMoreMetrics: '更多指标',
  overviewP95: 'p95 延迟',
  overviewNoError: '暂无错误记录',
  overviewModelDescription: '网关对外提供的模型及其上游目标。',
  overviewManageRoutes: '管理路由',
  overviewModelsCount: '{n} 个模型',
  overviewNoModels: '暂时没有可用模型',
  overviewNoModelsDescription: '配置中转站与模型路由后，可用模型会显示在这里。',
  overviewDirectModel: '可通过网关调用',
}
