export const shellEn = {
  workspaceLabel: 'Workspace',
  gatewayLabel: 'Personal gateway',
  localWorkspace: 'Local workspace',
  navigationLabel: 'Main navigation',
  skipToContent: 'Skip to content',
  refreshView: 'Refresh status',
  serviceActions: 'Service controls',
  serviceActionsNote: 'Manage the running gateway and its telemetry.',
  reloadNote: 'Read the saved configuration from disk.',
  resetNote: 'Clear the gateway’s traffic counters and statistics.',
  shutdownNote: 'Stop this gateway. Start it again from the command line.',
  confirmReloadDraft: 'Reloading will discard your unsaved changes. Continue?',
  languageTitle: 'Switch language',
  appearanceLabel: 'Appearance',
  languageLabel: 'Language',
  accessLabel: 'Access key',
  close: 'Close',
  savingChanges: 'Saving…',
  draftNote: 'Your edits are ready to apply.',
  savedConfigLabel: 'Configuration saved',
  connectionLost: 'Cannot reach the gateway',
  connectionLostNote: 'Check that the service is running, or update your access key.',
  connectingGateway: 'Connecting to your gateway',
  connectionInitialNote: 'Waiting for the local service. You can retry or enter an access key.',
  gatewayStatus: 'Gateway status',
  confirmResetStats: 'Reset all traffic counters and statistics?',
}
export const shellZh: Record<keyof typeof shellEn, string> = {
  workspaceLabel: '工作空间',
  gatewayLabel: '个人 AI 网关',
  localWorkspace: '本地工作空间',
  navigationLabel: '主导航',
  skipToContent: '跳转到内容',
  refreshView: '刷新状态',
  serviceActions: '服务控制',
  serviceActionsNote: '管理正在运行的网关与遥测数据。',
  reloadNote: '从磁盘重新读取已保存的配置。',
  resetNote: '清空网关的流量计数与统计数据。',
  shutdownNote: '停止当前网关，之后可通过命令行重新启动。',
  confirmReloadDraft: '重新加载会丢弃尚未保存的修改，是否继续？',
  languageTitle: '切换语言',
  appearanceLabel: '外观',
  languageLabel: '语言',
  accessLabel: '访问密钥',
  close: '关闭',
  savingChanges: '正在保存…',
  draftNote: '修改将在保存后生效。',
  savedConfigLabel: '配置已保存',
  connectionLost: '暂时无法连接网关',
  connectionLostNote: '请确认服务正在运行，或更新访问密钥。',
  connectingGateway: '正在连接你的网关',
  connectionInitialNote: '等待本地服务响应，你可以重试或输入访问密钥。',
  gatewayStatus: '网关状态',
  confirmResetStats: '是否清空所有流量计数与统计数据？',
}
