/** Copy for the provider and route workspace, composed into the main dictionaries. */
export const managementEn: Record<string, string> = {
  managementProbeHint: 'Checks the saved model-list endpoint and credentials; it does not test model generation.',
  managementRequiredProvider: "Enter a provider ID and base URL.",
  managementDuplicateProvider: "Provider ID {id} already exists.",
  managementInvalidUrl: "Enter a complete http:// or https:// base URL.",
  managementPriceModelRequired: "Enter a model name for each price row, or remove the empty row.",
  managementDuplicatePrice: "Model {model} has more than one price row.",
  managementInvalidPrice: "Token prices must be finite numbers of 0 or more.",
  managementInvalidTraffic: "Use whole numbers for traffic settings. Timeouts must be at least 1 second; request limits cannot be negative.",
  managementVertexRequired: "Vertex requires a project ID and a credentials file on the server.",
  managementBedrockRegionRequired: "Bedrock requires an AWS region.",
  managementRequiredRoute: "Enter a public model name and choose a provider for every target.",
  managementDuplicateRoute: "A route for {model} already exists.",
  managementUnknownTarget: "Provider {id} no longer exists. Choose a current provider or remove this target.",
  managementDiscardDialog: "Discard the changes in this editor? Changes already applied to the main draft will be kept.",
  managementIdLocked: "Saved IDs are fixed because routes and stored credentials use them. Edit the display name to rename this provider in the console.",
  managementHideKey: "Hide key",
  managementDiscoverModels: "Discover models",
  managementDiscoveryHint: "Read the model list using the saved connection. Select models to add to this draft; existing models stay in place. This does not test model generation.",
  managementNoDiscoveredModels: "The provider returned no model list. You can still enter model IDs above.",
  managementSelectAllModels: "Select all",
  managementImportModels: "Add {n} selected models",
  managementModelListHint: "One model ID per line. These names appear in the model list and are matched automatically when automatic routing is enabled. Explicit routes can use models not listed here.",
  managementStreamingHint: "When off, this provider is skipped for streaming requests. Non-streaming requests can still use it.",
  managementPriorityHint: "Lower values are preferred for automatic model matching. Explicit routes use their target order; fastest/cheapest policies may reorder the result.",
  managementWeightHint: "For automatic matches at the same priority, higher weight comes first. This is a tie-breaker, not a traffic percentage.",
  managementChatPathHint: "Keep /chat/completions to use the selected protocol’s default endpoint. A custom path overrides that default and is joined to the base URL.",
  managementEmbeddingsPathHint: "Used for embedding requests. The upstream endpoint must accept the OpenAI embeddings format; no embedding protocol conversion is performed.",
  managementConfirmDeleteReferencedProvider: "Delete provider {id}? This also removes {targets} route targets and {routes} routes left with no targets ({models}). These changes take effect together after saving.",
  managementEditorConflict: "This item changed while the editor was open. Cancel and reopen it before applying your changes.",
  managementRoutingFastestHint: "The fastest policy ranks these targets by measured p95 latency. The listed order breaks ties; unmeasured targets come last.",
  managementRoutingCheapestHint: "The cheapest policy ranks these targets by input + output token price. The listed order breaks ties; unpriced targets come last.",
  managementAffinityHint: "Session affinity is enabled for {seconds} seconds and may move a conversation’s previous provider to the front.",
  managementDisabledRouteFallback: "This explicit route is disabled. Automatic matching is enabled, so the same model name may still reach providers that list it.",

  managementProviderIntro: 'Connect your AI providers and keep every upstream in one place.',
  managementTotalProviders: 'Total providers',
  managementEnabledProviders: 'Enabled providers',
  managementProtocols: 'Protocols',
  managementSearchProviders: 'Search providers or models…',
  managementFilterStatus: 'Filter by provider status',
  managementFilterall: 'All providers',
  managementFilterenabled: 'Enabled',
  managementFilterdisabled: 'Disabled',
  managementKeyConfigured: 'Key configured',
  managementToggleProvider: 'Enable provider {id}',
  managementRemoveProvider: 'Remove provider {id}',
  managementEnabled: 'Enabled',
  managementDisabled: 'Disabled',
  managementPriority: 'Priority',
  managementNoModels: 'No models configured',
  managementSaveToProbe: 'Apply and save this connection before testing it.',
  managementNoMatches: 'No matching results',
  managementNoMatchesHint: 'Try a different search or clear your filters.',
  managementEmptyProviders: 'Your first connection starts here',
  managementEmptyProvidersHint: 'Add an upstream provider to connect your models to literouter.',
  managementResetFilters: 'Clear filters',
  managementRouteIntro: 'Give your models a single name and a reliable path to every provider.',
  managementFailoverTitle: 'Configured target order',
  managementSearchRoutes: 'Search models or target providers…',
  managementTargetCount: '{n} targets in the chain',
  managementToggleRoute: 'Enable route {model}',
  managementEditRoute: 'Edit route {model}',
  managementRemoveRoute: 'Remove route {model}',
  managementPrimary: 'Configured first',
  managementFallback: 'Fallback',
  managementMissingProvider: 'Provider missing',
  managementNoTargets: 'No targets configured',
  managementRouteDisabled: 'This route is disabled.',
  managementEmptyRoutes: 'Build a route for your model',
  managementEmptyRoutesHint: 'Map a model name to one or more providers, then choose the order they are tried.',
  managementConnection: 'Connection',
  managementModelsPricing: 'Models',
  managementTraffic: 'Traffic',
  managementAdvanced: 'Advanced',
  managementProviderDialogHint: 'Connection, models and traffic controls for your upstream provider.',
  managementProviderSections: 'Provider settings sections',
  managementProviderId: 'Provider ID',
  managementDisplayName: 'Display name',
  managementProtocol: 'Protocol',
  managementAvailability: 'Availability',
  managementProviderEnabled: 'Enable this provider',
  managementApiVersion: 'API version',
  managementRegion: 'Region',
  managementProject: 'Project ID',
  managementCredentialsFile: 'Credentials file',
  managementAwsAccessKey: 'AWS access key ID',
  managementAwsSecret: 'AWS secret access key',
  managementAwsSession: 'AWS session token',
  managementStreaming: 'Streaming',
  managementSupportsStreaming: 'Supports streaming responses',
  managementPricing: 'Token pricing',
  managementDefaultPricing: 'Default token pricing',
  managementDefaultPricingHint: 'Applied to all models on this provider unless overridden below. 0 means unpriced.',
  managementInputPrice: 'Input · USD / 1M tokens',
  managementOutputPrice: 'Output · USD / 1M tokens',
  managementModelPricing: 'Model-specific pricing',
  managementModelPricingHint: 'Model overrides are matched by upstream name first, then the public model name. They determine cost estimates and cheapest-policy ordering.',
  managementAddModelPrice: 'Add model price',
  managementRemoveModelPrice: 'Remove model price',
  managementModelName: 'Model name',
  managementNoModelPrices: 'No model-specific prices set yet. All models use the default price.',
  managementWeight: 'Weight',
  managementRequestTimeout: 'Request timeout (seconds)',
  managementConnectTimeout: 'Connection timeout (seconds)',
  managementConcurrency: 'Concurrent request limit',
  managementRequestsMinute: 'Requests per minute',
  managementHeaders: 'Custom headers',
  managementChatPath: 'Chat endpoint path',
  managementEmbeddingsPath: 'Embeddings endpoint path',
  managementNote: 'Notes',
  managementDraftHint: 'Save your changes to make them live.',
  managementRouteDialogHint: 'Choose a model name and arrange its upstream providers.',
  managementPublicModel: 'Public model name',
  managementPublicModelHint: 'The model name your clients use when sending a request.',
  managementAddProviderFirst: 'Add a provider first, then select it as a route target.',
  managementMoveTargetUp: 'Move target {n} up',
  managementMoveTargetDown: 'Move target {n} down',
  managementRemoveTarget: 'Remove target {n}',
  managementTargetProviderLabel: 'Provider for target {n}',
  managementSelectProvider: 'Select a provider',
  managementUpstreamModel: 'Upstream model (optional)',
  managementKeepModel: 'Keep the public model name',
  managementTargetModelLabel: 'Upstream model for target {n}',
}

export const managementZh: Record<string, string> = {
  managementProbeHint: '检查已保存的模型列表接口与凭据，不测试模型生成能力。',
  managementRequiredProvider: "请填写中转站标识与基础地址。",
  managementDuplicateProvider: "中转站标识 {id} 已存在。",
  managementInvalidUrl: "请填写完整的 http:// 或 https:// 基础地址。",
  managementPriceModelRequired: "请填写每条价格对应的模型名称，或移除空行。",
  managementDuplicatePrice: "模型 {model} 存在重复的价格条目。",
  managementInvalidPrice: "Token 价格必须为大于或等于 0 的有效数字。",
  managementInvalidTraffic: "流量设置请使用整数。超时至少为 1 秒，请求上限不能为负数。",
  managementVertexRequired: "Vertex 需要项目 ID 与服务端凭据文件路径。",
  managementBedrockRegionRequired: "Bedrock 需要填写 AWS 区域。",
  managementRequiredRoute: "请填写对外模型名称，并为每个候选目标选择中转站。",
  managementDuplicateRoute: "模型 {model} 的路由已存在。",
  managementUnknownTarget: "中转站 {id} 已不存在，请重新选择或移除此候选目标。",
  managementDiscardDialog: "放弃当前编辑窗口中的修改？已应用到主草稿的修改会保留。",
  managementIdLocked: "已保存的标识用于路由与密钥关联，不可修改。可通过显示名称调整控制台中的名称。",
  managementHideKey: "隐藏密钥",
  managementDiscoverModels: "发现模型",
  managementDiscoveryHint: "使用已保存的连接读取模型列表。勾选后加入当前草稿，保留已有模型。此操作不测试模型生成能力。",
  managementNoDiscoveredModels: "中转站未返回模型列表，仍可在上方手动填写模型标识。",
  managementSelectAllModels: "全选",
  managementImportModels: "加入已选的 {n} 个模型",
  managementModelListHint: "每行一个模型标识。模型会出现在模型列表中，并在启用自动匹配时参与选站。显式路由也可调用未列在此处的模型。",
  managementStreamingHint: "关闭后，流式请求会跳过此中转站；非流式请求仍可使用。",
  managementPriorityHint: "自动匹配模型时，数值越小越优先。显式路由按候选顺序；最快或最便宜策略可能重新排序。",
  managementWeightHint: "自动匹配且优先级相同时，权重越大越靠前。它用于同级排序，不是流量百分比。",
  managementChatPathHint: "保留 /chat/completions 时使用所选协议的默认接口。自定义路径会替代默认接口，并与基础地址拼接。",
  managementEmbeddingsPathHint: "用于向量请求。上游接口需兼容 OpenAI embeddings 格式，此处不进行向量协议转换。",
  managementConfirmDeleteReferencedProvider: "删除中转站 {id}？同时移除 {targets} 个路由候选目标，并删除因此不再有候选目标的 {routes} 条路由（{models}）。这些修改将在保存后一起生效。",
  managementEditorConflict: "编辑期间此条目已发生变化，请取消并重新打开后再应用修改。",
  managementRoutingFastestHint: "当前使用最快策略，候选按已测得的 p95 延迟排序；列表顺序用于同分排序，尚无测量数据的目标排后。",
  managementRoutingCheapestHint: "当前使用最便宜策略，候选按输入与输出 Token 单价之和排序；列表顺序用于同价排序，未定价目标排后。",
  managementAffinityHint: "会话亲和已启用，有效期为 {seconds} 秒，可能优先使用该会话上一次的中转站。",
  managementDisabledRouteFallback: "此显式路由已停用。当前仍启用自动匹配，同名模型可能继续通过列有该模型的中转站调用。",

  managementProviderIntro: '连接你的 AI 服务，在一个地方管理所有上游中转站。',
  managementTotalProviders: '全部中转站',
  managementEnabledProviders: '已启用',
  managementProtocols: '接入协议',
  managementSearchProviders: '搜索中转站或模型…',
  managementFilterStatus: '按中转站状态筛选',
  managementFilterall: '全部中转站',
  managementFilterenabled: '已启用',
  managementFilterdisabled: '已停用',
  managementKeyConfigured: '已填写密钥',
  managementToggleProvider: '启用中转站 {id}',
  managementRemoveProvider: '移除中转站 {id}',
  managementEnabled: '已启用',
  managementDisabled: '已停用',
  managementPriority: '优先级',
  managementNoModels: '尚未配置模型',
  managementSaveToProbe: '应用并保存当前连接设置后，即可探测。',
  managementNoMatches: '没有找到匹配的结果',
  managementNoMatchesHint: '试试其他关键词，或清除筛选条件。',
  managementEmptyProviders: '从第一个连接开始',
  managementEmptyProvidersHint: '添加一个上游中转站，将你的模型接入 literouter。',
  managementResetFilters: '清除筛选',
  managementRouteIntro: '统一模型名称，清晰安排每一次请求的转发路径。',
  managementFailoverTitle: '候选配置顺序',
  managementSearchRoutes: '搜索模型或候选中转站…',
  managementTargetCount: '候选链包含 {n} 个目标',
  managementToggleRoute: '启用路由 {model}',
  managementEditRoute: '编辑路由 {model}',
  managementRemoveRoute: '移除路由 {model}',
  managementPrimary: '配置首位',
  managementFallback: '备用',
  managementMissingProvider: '中转站不存在',
  managementNoTargets: '尚未配置候选目标',
  managementRouteDisabled: '此路由已停用。',
  managementEmptyRoutes: '为模型建立一条路由',
  managementEmptyRoutesHint: '将一个模型名称映射到多个中转站，并安排它们的尝试顺序。',
  managementConnection: '连接设置',
  managementModelsPricing: '模型与定价',
  managementTraffic: '流量控制',
  managementAdvanced: '高级设置',
  managementProviderDialogHint: '配置上游连接、可用模型与流量规则。',
  managementProviderSections: '中转站设置分类',
  managementProviderId: '中转站标识',
  managementDisplayName: '显示名称',
  managementProtocol: '协议',
  managementAvailability: '启用状态',
  managementProviderEnabled: '启用此中转站',
  managementApiVersion: 'API 版本',
  managementRegion: '区域',
  managementProject: '项目 ID',
  managementCredentialsFile: '凭据文件',
  managementAwsAccessKey: 'AWS Access Key ID',
  managementAwsSecret: 'AWS Secret Access Key',
  managementAwsSession: 'AWS 会话令牌',
  managementStreaming: '流式响应',
  managementSupportsStreaming: '支持流式响应',
  managementPricing: 'Token 定价',
  managementDefaultPricing: '默认基础价格（总的）',
  managementDefaultPricingHint: '中转站下未单独设置价格的模型将使用此默认价格。0 表示未设置。',
  managementInputPrice: '输入 · 美元 / 百万 Token',
  managementOutputPrice: '输出 · 美元 / 百万 Token',
  managementModelPricing: '模型单独价格',
  managementModelPricingHint: '优先按上游模型名匹配，再按对外模型名匹配。价格用于费用估算与最便宜策略排序。',
  managementAddModelPrice: '添加模型价格',
  managementRemoveModelPrice: '移除模型价格',
  managementModelName: '模型名称',
  managementNoModelPrices: '暂未设置模型单独价格，所有模型均使用上方默认价格。',
  managementWeight: '权重',
  managementRequestTimeout: '请求超时（秒）',
  managementConnectTimeout: '连接超时（秒）',
  managementConcurrency: '并发请求上限',
  managementRequestsMinute: '每分钟请求上限',
  managementHeaders: '自定义请求头',
  managementChatPath: '对话接口路径',
  managementEmbeddingsPath: '向量接口路径',
  managementNote: '备注',
  managementDraftHint: '保存修改后生效。',
  managementRouteDialogHint: '设置模型名称，并安排上游中转站的尝试顺序。',
  managementPublicModel: '对外模型名称',
  managementPublicModelHint: '客户端发送请求时使用的模型名称。',
  managementAddProviderFirst: '请先添加中转站，再将其选为路由候选目标。',
  managementMoveTargetUp: '上移第 {n} 个目标',
  managementMoveTargetDown: '下移第 {n} 个目标',
  managementRemoveTarget: '移除第 {n} 个目标',
  managementTargetProviderLabel: '第 {n} 个目标的中转站',
  managementSelectProvider: '选择中转站',
  managementUpstreamModel: '上游模型（可选）',
  managementKeepModel: '沿用对外模型名称',
  managementTargetModelLabel: '第 {n} 个目标的上游模型',
}
